import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Merriweather, Raleway } from "next/font/google";

const merriweather = Merriweather({
  subsets: ["latin"],
  weight: ["400", "700"], // Add desired weights
  variable: "--font-merriweather", // Define a CSS variable
});

const raleway = Raleway({
  subsets: ["latin"],
  weight: ["400", "600"], // Add desired weights
  variable: "--font-raleway", // Define a CSS variable
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${merriweather.variable} ${raleway.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
